'use strict';
const $=id=>document.getElementById(id);
const canvas=$('stage'),ctx=canvas.getContext('2d');
let mode='home',floor=0,collected=0,firstCorrect=0,activeQ=-1,attempts=0,locked=false,solved=new Set(),mistakes=new Set(),keys={},lastTime=0,t=0,camera=0,W=1280,H=620,paused=false,checkpoint=95,invincible=0,soundOn=true,audioContext=null,filmIndex=0,toastUntil=0,transition=false;
let chapter=0,gateCount=12,filmPurpose='intro',gardenReturn='cinema',gardenTime=0,musicChapter=-1;
function currentFloors(){return chapter===1?GARDEN_FLOORS:FLOORS;}
let rounds=[],roundIndex=0,activeGate=-1,totalQuestions=12,answered=new Set();
let cat={x:95,y:440,vx:0,vy:0,onGround:false,face:1};
const groundY=492,worldWidth=2210,gates=[660,1300,1940],gaps=[[425,515],[1065,1155],[1705,1795]],films=['tower-entry'],filmNames=['時間之塔'];
function syncMusic(){const music=$('bgm');if(musicChapter!==chapter){music.pause();music.src=chapter===1?'assets/garden-nocturne.mp3':'assets/tower-groove-soft.mp3';musicChapter=chapter;}music.volume=$('question').open?.16:.40;if(soundOn&&mode==='game'&&!paused&&!document.hidden)music.play().catch(()=>{});else music.pause();}
const img=new Image();img.src='assets/interior.jpg';
function screen(id){document.querySelectorAll('.screen').forEach(el=>el.classList.toggle('hidden',el.id!==id));mode=id;syncMusic();if(id!=='cinema')$('film').pause();if(id==='game'){resize();lastTime=0;}window.scrollTo({top:0,behavior:'instant'});}
function resize(){if(mode!=='game')return;const r=canvas.getBoundingClientRect();W=Math.max(440,Math.round(r.width/r.height*H));canvas.width=W;canvas.height=H;}
window.addEventListener('resize',resize);
function audio(){if(!soundOn)return null;try{audioContext??=new(window.AudioContext||window.webkitAudioContext)();audioContext.resume();return audioContext;}catch{return null;}}
function tone(freq,duration=.15,type='sine',delay=0){const a=audio();if(!a)return;const o=a.createOscillator(),g=a.createGain(),s=a.currentTime+delay;o.type=type;o.frequency.setValueAtTime(freq,s);g.gain.setValueAtTime(0,s);g.gain.linearRampToValueAtTime(.055,s+.015);g.gain.exponentialRampToValueAtTime(.001,s+duration);o.connect(g);g.connect(a.destination);o.start(s);o.stop(s+duration);}
function chime(){[523,659,784,1047].forEach((n,i)=>tone(n,.3,'sine',i*.09));}
$('sound').onclick=()=>{soundOn=!soundOn;$('sound').innerHTML='♪ <span>音效'+(soundOn?'開':'關')+'</span>';$('sound').setAttribute('aria-pressed',soundOn);$('sound').setAttribute('aria-label',soundOn?'關閉音效':'開啟音效');$('film').muted=!soundOn;syncMusic();if(soundOn)tone(660);};
function playFilm(waitForTap=false){const v=$('film');v.src=filmPurpose==='interlude'?'assets/interlude.mp4':'assets/'+films[filmIndex]+'.mp4';v.poster=filmPurpose==='interlude'?'':'assets/snow.jpg';$('skip').textContent=filmPurpose==='interlude'?'Skip · 略過過場 →':'Skip · 略過序幕 →';$('cinema').classList.toggle('portrait-film',filmPurpose==='interlude');v.muted=!soundOn;v.volume=.85;$('resume-film').innerHTML='<svg class="paw-mark" viewBox="0 0 80 80" aria-hidden="true"><ellipse cx="17" cy="30" rx="9" ry="12" transform="rotate(-25 17 30)"/><ellipse cx="33" cy="18" rx="9" ry="12" transform="rotate(-8 33 18)"/><ellipse cx="52" cy="20" rx="9" ry="12" transform="rotate(12 52 20)"/><ellipse cx="66" cy="34" rx="8" ry="11" transform="rotate(30 66 34)"/><path d="M23 46C29 31 48 31 55 46C60 52 68 62 61 69C54 77 46 69 40 69C34 69 25 77 18 69C11 62 17 53 23 46Z"/></svg><span>'+(filmPurpose==='interlude'?'轉開第二道輪盤':'揭開序幕')+'</span>';$('chapter-number').textContent=filmPurpose==='interlude'?'INTERLUDE':'PROLOGUE 0'+(filmIndex+1);$('chapter-name').textContent=filmPurpose==='interlude'?'第二道輪盤':filmNames[filmIndex];if(waitForTap){v.pause();$('resume-film').classList.remove('hidden');return;}$('resume-film').classList.add('hidden');v.play().catch(()=>$('resume-film').classList.remove('hidden'));}
function intro(waitForTap=true){filmPurpose='intro';filmIndex=0;screen('cinema');playFilm(waitForTap);}
function afterFilm(){if(filmPurpose==='interlude')screen('ending');else newGame(0);}
function playInterlude(){filmPurpose='interlude';screen('cinema');playFilm();}
$('film').onended=afterFilm;
$('film').onerror=()=>{$('resume-film').textContent='影片暫時無法播放，繼續冒險 →';$('resume-film').classList.remove('hidden');};
$('resume-film').onclick=()=>{if($('film').error)afterFilm();else $('film').play().then(()=>$('resume-film').classList.add('hidden')).catch(()=>{});};
$('start').onclick=()=>intro(false);$('direct').onclick=()=>newGame(0);$('skip').onclick=afterFilm;$('again').onclick=()=>newGame(chapter);$('replay').onclick=intro;
function gardenIntro(){if(mode==='garden-intro')return;if($('question').open||$('pause-dialog').open)return;gardenReturn=mode;keys={};screen('garden-intro');}
$('garden-access').onclick=gardenIntro;$('next-chapter').onclick=gardenIntro;$('garden-start').onclick=()=>newGame(1);$('garden-back').onclick=()=>{screen(gardenReturn);if(gardenReturn==='cinema')$('resume-film').classList.remove('hidden');};$('replay-interlude').onclick=playInterlude;
function newGame(which=chapter){chapter=which===1?1:0;gateCount=chapter===1?9:12;floor=0;collected=0;firstCorrect=0;solved=new Set();mistakes=new Set();transition=false;paused=false;activeQ=-1;activeGate=-1;roundIndex=0;rounds=buildRounds();totalQuestions=rounds.reduce((n,r)=>n+r.length,0);answered=new Set();if($('pause-dialog').open)$('pause-dialog').close();if($('question').open)$('question').close();screen('game');loadFloor();}
function loadFloor(){gardenTime=0;checkpoint=95;cat={x:95,y:groundY-40,vx:0,vy:0,onGround:true,face:1};camera=0;keys={};invincible=1;updateHUD();$('floor-banner').textContent=currentFloors()[floor].title;$('floor-banner').classList.remove('hidden');setTimeout(()=>$('floor-banner').classList.add('hidden'),1700);toast(currentFloors()[floor].note+(chapter===0&&floor===2?' · 每個機關 2–3 題':''),3500);if(chapter===1)toast(currentFloors()[floor].title+' · '+gardenHints[floor],4500);}
function updateHUD(){$('shard-label').textContent=chapter===1?'可能之種':'時間碎片';$('floor-en').textContent='0'+(floor+1)+' / '+currentFloors()[floor].en;$('floor-title').textContent=currentFloors()[floor].title;$('progress').innerHTML=collected+' <i>/ '+gateCount+'</i>';$('score').innerHTML=firstCorrect+' <i>/ '+totalQuestions+'</i>';$('floor-dots').innerHTML=Array.from({length:gateCount},(_,i)=>'<span class="dot '+(solved.has(i)?'done':'')+'"></span>').join('');}
function toast(s,ms=2200){$('toast').textContent=s;$('toast').classList.add('visible');toastUntil=performance.now()+ms;}
function jump(){if(mode!=='game'||paused||$('question').open||transition)return;if(cat.onGround){cat.vy=-600;cat.onGround=false;tone(400,.12,'triangle');}}
function nearGate(){return gates.findIndex((g,i)=>!solved.has(floor*3+i)&&Math.abs(cat.x-(g-72))<108&&cat.y>330);}
function buildRounds(random=Math.random){if(chapter===1)return Array.from({length:9},(_,i)=>[18+i]);return Array.from({length:12},(_,gate)=>{if(gate<6||gate>8)return[gate];const extras=[12+(gate-6)*2,13+(gate-6)*2];if(random()<.5)extras.reverse();return[gate,...extras.slice(0,random()<.5?1:2)];});}
function showQuestion(){activeQ=rounds[activeGate][roundIndex];attempts=0;locked=false;const q=QUESTIONS[activeQ],count=rounds[activeGate].length;$('q-label').textContent='機關 '+String(activeGate+1).padStart(2,'0')+' / '+gateCount+(count>1?'  ·  完成式 '+(roundIndex+1)+' / '+count+' 題':'');$('q-title').textContent=count>1?'完成式連續挑戰':chapter===1?'讓另一種可能開花':'喚醒時間機關';$('q-context').textContent=q.context;$('q-text').innerHTML=q.text.replaceAll('___','<span class="blank">_____</span>');$('options').replaceChildren();q.options.forEach((s,i)=>{const b=document.createElement('button'),tag=document.createElement('span');tag.textContent='ABCD'[i];b.append(tag,document.createTextNode(s));b.onclick=()=>answer(i,b);$('options').appendChild(b);});$('feedback').classList.add('hidden');$('continue').classList.add('hidden');$('q-note').textContent=count>1?'本機關共 '+count+' 題，全部答對後開門。選錯可重試，不計時。':'慢慢想，不計時。選錯可以再試一次。';if(!$('question').open)$('question').showModal();syncMusic();}
function interact(){if(mode!=='game'||paused||transition||$('question').open)return;const n=nearGate();if(n<0)return;activeGate=floor*3+n;roundIndex=0;keys={};showQuestion();}
function answer(i,b){if(locked||answered.has(activeQ))return;const q=QUESTIONS[activeQ];attempts++;$('feedback').classList.remove('hidden');if(i===q.answer){locked=true;answered.add(activeQ);b.classList.add('correct');for(const el of $('options').children)el.disabled=true;if(attempts===1)firstCorrect++;const complete=roundIndex===rounds[activeGate].length-1;if(complete){solved.add(activeGate);collected=solved.size;}$('feedback').textContent='✓ '+q.why;$('continue').textContent=complete?(chapter===1?'收集種子，繼續前進 →':'收集碎片，繼續前進 →'):'下一題（'+(roundIndex+2)+' / '+rounds[activeGate].length+'）→';$('continue').classList.remove('hidden');$('q-title').textContent=complete?(chapter===1?'一顆可能之種，發芽了':'時間碎片，甦醒了'):'齒輪已轉動，再解下一題';if(complete)chime();else tone(660,.2);updateHUD();}else{mistakes.add(activeQ);b.classList.add('wrong');b.disabled=true;$('feedback').textContent='再想一下：'+q.clue+'。試著把選項放回完整句子裡。';tone(180,.22,'triangle');}}
$('continue').onclick=()=>{if(!locked)return;if(roundIndex<rounds[activeGate].length-1){roundIndex++;showQuestion();return;}$('question').close();syncMusic();checkpoint=gates[activeGate%3]+55;activeQ=-1;activeGate=-1;toast(chapter===1?'✦ 可能之種已收集，花門開啟！':'✦ 碎片已收集，光門開啟！');keys={};};
$('question').addEventListener('cancel',e=>e.preventDefault());$('interact').onclick=interact;
function pause(){if(mode!=='game'||$('question').open||transition)return;paused=true;keys={};syncMusic();$('pause-dialog').showModal();}
$('pause').onclick=pause;$('resume').onclick=()=>{$('pause-dialog').close();paused=false;syncMusic();lastTime=0;};$('pause-dialog').addEventListener('cancel',()=>{paused=false;syncMusic();keys={};});$('restart').onclick=()=>newGame(chapter);
window.addEventListener('keydown',e=>{if(mode!=='game')return;if(['ArrowLeft','ArrowRight','ArrowUp',' ','e','E','Escape'].includes(e.key))e.preventDefault();if(e.key==='Escape'){if($('question').open)return;if(paused){$('pause-dialog').close();paused=false;syncMusic();}else pause();return;}if(paused||$('question').open)return;keys[e.key]=true;if(!e.repeat&&(e.key===' '||e.key==='ArrowUp'))jump();if(!e.repeat&&e.key.toLowerCase()==='e')interact();});
window.addEventListener('keyup',e=>keys[e.key]=false);window.addEventListener('blur',()=>{keys={};if(mode==='game'&&!paused&&!$('question').open)pause();});document.addEventListener('visibilitychange',()=>{syncMusic();if(document.hidden){keys={};if(mode==='game'&&!paused&&!$('question').open)pause();}});
function hold(id,key){const b=$(id);b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys[key]=true;};for(const name of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(name,()=>keys[key]=false);}
hold('left','ArrowLeft');hold('right','ArrowRight');$('jump').onpointerdown=e=>{e.preventDefault();jump();};
// Safari can open its copy/callout menu on a held control without these guards.
document.querySelectorAll('.stage-wrap, .control-bar').forEach(area=>{
  for(const type of ['contextmenu','selectstart'])area.addEventListener(type,e=>e.preventDefault());
});
function respawn(){cat.x=checkpoint;cat.y=groundY-40;cat.vy=0;cat.onGround=true;invincible=2;toast('回到安全點，再抓一次跳躍時機。');tone(160,.2,'triangle');}
function hazard(i){const ax=890+i*640,ang=Math.sin(t*1.7+i)*.65;return{x:ax+Math.sin(ang)*225,y:200+Math.cos(ang)*225,ax,ang};}
function update(dt){t+=dt;invincible=Math.max(0,invincible-dt);if(performance.now()>toastUntil)$('toast').classList.remove('visible');if(paused||$('question').open||transition)return;gardenTime+=dt;cat.vx=((keys.ArrowRight||keys.d?1:0)-(keys.ArrowLeft||keys.a?1:0))*285;if(cat.vx)cat.face=Math.sign(cat.vx);const oldY=cat.y;cat.x=Math.max(25,Math.min(worldWidth-35,cat.x+cat.vx*dt));cat.vy+=1600*dt;cat.y+=cat.vy*dt;cat.onGround=false;const inGap=gaps.some(([a,b])=>cat.x>a+10&&cat.x<b-10);if(!inGap&&oldY+40<=groundY+5&&cat.y+40>=groundY&&cat.vy>=0){cat.y=groundY-40;cat.vy=0;cat.onGround=true;}
for(let i=0;i<3;i++){if(!solved.has(floor*3+i)&&cat.x>gates[i]-23){cat.x=gates[i]-23;cat.vx=0;break;}}
for(let i=0;i<2;i++){if(chapter===1){if(invincible<=0&&gardenHit(gardenHazard(i)))respawn();}else{const h=hazard(i);if(invincible<=0&&Math.hypot(cat.x-h.x,cat.y-h.y)<48)respawn();}}if(cat.y>H+100)respawn();
camera=Math.max(0,Math.min(worldWidth-W,cat.x-W*.32));camera=Math.max(0,camera);const near=nearGate();$('interact').classList.toggle('hidden',near<0);$('stage-hint').textContent=near>=0?(chapter===0&&floor===2?'完成式機關 · 本組 '+rounds[floor*3+near].length+' 題 · 按 E 啟動':chapter===1?'花之封印就在眼前 · 按 E 啟動':'時態轉盤就在眼前 · 按 E 啟動'):solved.has(floor*3+2)?'光門已開啟，向右走進下一層':(chapter===1?gardenHints[floor]:(floor===1||floor===2)?'留意吸塵器幽靈與噴霧鐘擺':'跳過缺口，留意擺動的鐘擺');
if(cat.x>worldWidth-90&&solved.has(floor*3+2)){transition=true;chime();if(floor===currentFloors().length-1)setTimeout(finish,500);else{floor++;setTimeout(()=>{transition=false;loadFloor();},350);}}}
function gear(x,y,r,angle,alpha=1){ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.globalAlpha*=alpha;ctx.fillStyle='#ae8546';ctx.strokeStyle='#f0cc7b';ctx.lineWidth=2;ctx.beginPath();for(let j=0;j<80;j++){const a=j/80*Math.PI*2,rr=j%4<2?r:r*.88;const xx=Math.cos(a)*rr,yy=Math.sin(a)*rr;j?ctx.lineTo(xx,yy):ctx.moveTo(xx,yy);}ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle='#302b30';ctx.beginPath();ctx.arc(0,0,r*.66,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#c79c57';ctx.lineWidth=r*.09;for(let j=0;j<6;j++){ctx.rotate(Math.PI/3);ctx.beginPath();ctx.moveTo(r*.16,0);ctx.lineTo(r*.68,0);ctx.stroke();}ctx.fillStyle='#c49a5a';ctx.beginPath();ctx.arc(0,0,r*.17,0,Math.PI*2);ctx.fill();ctx.restore();}
function roundRect(x,y,w,h,r,fill){ctx.fillStyle=fill;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill();}
function drawCat(x,y){ctx.save();ctx.translate(x,y);ctx.scale(cat.face,1);if(invincible>0&&Math.floor(t*12)%2===0)ctx.globalAlpha=.55;
const moving=Math.min(1,Math.abs(cat.vx)/160),run=cat.onGround?Math.sin(t*16)*moving:0,bob=cat.onGround?Math.abs(run)*2:-2;
ctx.translate(0,bob);ctx.lineCap='round';ctx.lineJoin='round';
function oval(cx,cy,rx,ry,color){ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(cx,cy,rx,ry,0,0,Math.PI*2);ctx.fill();}
// Soft curled tail, with a cream tip.
ctx.strokeStyle='#8e542c';ctx.lineWidth=13;ctx.beginPath();ctx.moveTo(-14,21);ctx.bezierCurveTo(-44,28,-48,4,-39,-4+run*2);ctx.stroke();ctx.strokeStyle='#efa548';ctx.lineWidth=10;ctx.stroke();ctx.strokeStyle='#ffdeaa';ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(-42,5);ctx.quadraticCurveTo(-44,-1,-39,-4+run*2);ctx.stroke();
// Short paws keep the silhouette compact.
for(const s of [-1,1]){const px=s*11+run*s*6;oval(px,33-bob,9,8,'#ac6930');oval(px+1,31-bob,8,7,'#ffcc83');oval(px+3,34-bob,5,3,'#ffe4b6');}
const body=ctx.createLinearGradient(-18,0,19,35);body.addColorStop(0,'#ffcb79');body.addColorStop(1,'#d98434');oval(0,13,20,23,body);oval(5,16,11,14,'#ffe4b2');
// Emerald cloak, gold clasp, and tiny adventure satchel.
ctx.fillStyle='#123f3c';ctx.beginPath();ctx.moveTo(-18,-7);ctx.quadraticCurveTo(-28,4,-32-moving*8,25);ctx.quadraticCurveTo(-16,33,-6,25);ctx.lineTo(5,-3);ctx.closePath();ctx.fill();ctx.fillStyle='#287a61';ctx.beginPath();ctx.moveTo(-18,-7);ctx.lineTo(-27-moving*6,23);ctx.quadraticCurveTo(-15,24,-9,18);ctx.lineTo(1,-5);ctx.closePath();ctx.fill();ctx.strokeStyle='#bb9660';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-17,3);ctx.lineTo(13,26);ctx.stroke();roundRect(7,20,14,12,4,'#795032');roundRect(8,20,12,5,3,'#aa7745');oval(14,25,2,2,'#efce82');
ctx.save();ctx.translate(2,-3);ctx.scale(1.02,.94);
// Compact ears with soft tips, retaining the alert adventurer silhouette.
ctx.fillStyle='#d59951';ctx.beginPath();ctx.moveTo(-25,-31);ctx.bezierCurveTo(-29,-40,-29,-50,-26,-53);ctx.quadraticCurveTo(-21,-54,-10,-41);ctx.lineTo(12,-41);ctx.quadraticCurveTo(25,-54,28,-53);ctx.quadraticCurveTo(32,-50,27,-31);ctx.closePath();ctx.fill();
ctx.fillStyle='#e9b5a0';ctx.beginPath();ctx.moveTo(-25,-48);ctx.quadraticCurveTo(-24,-40,-20,-36);ctx.lineTo(-14,-41);ctx.quadraticCurveTo(-21,-49,-25,-49);ctx.fill();ctx.beginPath();ctx.moveTo(26,-48);ctx.lineTo(23,-35);ctx.lineTo(16,-41);ctx.quadraticCurveTo(23,-49,26,-49);ctx.fill();
const fur=ctx.createRadialGradient(-9,-34,3,5,-22,35);fur.addColorStop(0,'#f8d49b');fur.addColorStop(.55,'#e8b36c');fur.addColorStop(1,'#c58b4e');
ctx.beginPath();ctx.moveTo(-22,-39);ctx.quadraticCurveTo(-10,-47,2,-44);ctx.quadraticCurveTo(16,-46,25,-37);ctx.bezierCurveTo(30,-30,32,-19,30,-13);ctx.quadraticCurveTo(31,-3,21,3);ctx.quadraticCurveTo(13,11,2,10);ctx.quadraticCurveTo(-9,11,-18,4);ctx.quadraticCurveTo(-30,0,-29,-11);ctx.bezierCurveTo(-32,-23,-29,-33,-22,-39);ctx.closePath();ctx.fillStyle=fur;ctx.fill();
// Short soft tabby markings, without heavy cheek lines.
ctx.strokeStyle='#b8854b';ctx.lineWidth=1.3;for(const side of [-1,1]){ctx.beginPath();ctx.moveTo(side*11,-41);ctx.quadraticCurveTo(side*8,-38,side*7,-34);ctx.moveTo(side*3,-42);ctx.lineTo(side*3,-36);ctx.moveTo(side*28,-20);ctx.lineTo(side*24,-18);ctx.stroke();}
// Light bridge narrows between the eyes then broadens into the muzzle.
const cream=ctx.createLinearGradient(0,-32,0,9);cream.addColorStop(0,'#e9cc9b');cream.addColorStop(.6,'#f5e6c7');cream.addColorStop(1,'#dfc7a0');ctx.fillStyle=cream;ctx.beginPath();ctx.moveTo(1,-34);ctx.bezierCurveTo(-2,-25,-2,-20,-6,-15);ctx.quadraticCurveTo(-20,-15,-19,-5);ctx.quadraticCurveTo(-15,4,-7,3);ctx.quadraticCurveTo(-5,10,3,9);ctx.quadraticCurveTo(11,10,13,3);ctx.quadraticCurveTo(24,0,21,-7);ctx.quadraticCurveTo(19,-14,10,-14);ctx.quadraticCurveTo(6,-24,5,-31);ctx.closePath();ctx.fill();
// Natural almond eyes: reduced size, muted green irises, slim vertical pupils.
for(const [ex,ey,rx,tilt]of [[-12,-26,8.3,.06],[15,-26,8.6,-.09]]){ctx.save();ctx.translate(ex,ey);ctx.rotate(tilt);const eyePath=()=>{ctx.beginPath();ctx.moveTo(-rx,.7);ctx.bezierCurveTo(-rx*.48,-7.5,rx*.5,-8.1,rx,-.8);ctx.bezierCurveTo(rx*.52,5.8,-rx*.48,5.8,-rx,.7);ctx.closePath();};eyePath();ctx.fillStyle='#8f9f73';ctx.fill();ctx.save();ctx.clip();const iris=ctx.createRadialGradient(0,-1,1,0,0,7);iris.addColorStop(0,'#afbb87');iris.addColorStop(.7,'#899d73');iris.addColorStop(1,'#536750');oval(.5,0,6,6.5,iris);oval(1,0,2.7,6.5,'#21372e');oval(-1.4,-2.9,1.55,1.55,'#fff8e7');oval(2.8,2.3,.65,.65,'#e7f4d5');ctx.restore();eyePath();ctx.strokeStyle='#5f4936';ctx.lineWidth=1.1;ctx.stroke();ctx.beginPath();ctx.moveTo(-rx,.7);ctx.bezierCurveTo(-rx*.48,-7.5,rx*.5,-8.1,rx,-.8);ctx.strokeStyle='#493b2d';ctx.lineWidth=1.6;ctx.stroke();ctx.restore();}
// Long nasal bridge, defined nose leather, whisker pads and a neutral mouth.
const nose=ctx.createLinearGradient(0,-13,0,-6);nose.addColorStop(0,'#d2a299');nose.addColorStop(1,'#9b6960');ctx.fillStyle=nose;ctx.beginPath();ctx.moveTo(-1,-12);ctx.quadraticCurveTo(3,-14,8,-12);ctx.quadraticCurveTo(7,-9,4,-7);ctx.quadraticCurveTo(1,-9,-1,-12);ctx.fill();ctx.strokeStyle='#80574e';ctx.lineWidth=.7;ctx.beginPath();ctx.moveTo(-2,-11);ctx.lineTo(0,-10);ctx.moveTo(8,-11);ctx.lineTo(6,-10);ctx.moveTo(4,-6);ctx.lineTo(4,-3);ctx.quadraticCurveTo(0,0,-4,-1);ctx.moveTo(4,-3);ctx.quadraticCurveTo(8,0,12,-1);ctx.stroke();
ctx.fillStyle='#af987980';for(const side of [-1,1])for(let i=0;i<3;i++){ctx.beginPath();ctx.arc(4+side*(8+i%2*3),-7+i*2,.45,0,7);ctx.fill();}
ctx.strokeStyle='#f8ebd2b0';ctx.lineWidth=.55;for(const side of [-1,1]){for(let i=0;i<3;i++){ctx.beginPath();ctx.moveTo(4+side*12,-6+i*2);ctx.quadraticCurveTo(side*26,-11+i*5,side*(32-i*2),-12+i*6);ctx.stroke();}}
ctx.restore();
ctx.fillStyle='#276852';ctx.beginPath();ctx.moveTo(-16,0);ctx.quadraticCurveTo(0,9,18,0);ctx.lineTo(10,8);ctx.quadraticCurveTo(0,12,-10,7);ctx.closePath();ctx.fill();oval(3,5,4,4,'#edcd79');oval(3,5,2,2,'#fff1b0');ctx.restore();}
function drawHauntedWeight(h,i){ctx.save();ctx.translate(h.x,h.y);ctx.rotate(-h.ang*.38);const close=Math.abs(cat.x-h.x)<180,glow=.45+.2*Math.sin(t*2+i);
if(close){ctx.save();ctx.globalAlpha=.16;const fog=ctx.createRadialGradient(0,0,4,0,0,65);fog.addColorStop(0,'#cb768b');fog.addColorStop(1,'#cb768b00');ctx.fillStyle=fog;ctx.beginPath();ctx.arc(0,0,65,0,7);ctx.fill();ctx.restore();}
if(i===0){
// A haunted vacuum brush with a hose, bristles and small glowing eyes.
ctx.strokeStyle='#595065';ctx.lineWidth=10;ctx.beginPath();ctx.moveTo(1,-28);ctx.bezierCurveTo(-28,-51,26,-56,6,-76);ctx.stroke();ctx.strokeStyle='#9d8799';ctx.lineWidth=1;for(let k=0;k<5;k++){ctx.beginPath();ctx.moveTo(-6,-33-k*6);ctx.lineTo(7,-36-k*6);ctx.stroke();}
const metal=ctx.createLinearGradient(-26,-24,20,23);metal.addColorStop(0,'#988b9d');metal.addColorStop(.35,'#574b64');metal.addColorStop(1,'#252735');roundRect(-27,-24,54,38,12,metal);roundRect(-34,10,68,13,5,'#303440');ctx.strokeStyle='#6e7380';ctx.lineWidth=2;for(let b=-28;b<=28;b+=5){ctx.beginPath();ctx.moveTo(b,22);ctx.lineTo(b+2,28);ctx.stroke();}
ctx.fillStyle='#1c202c';ctx.beginPath();ctx.moveTo(-20,-12);ctx.lineTo(-4,-6);ctx.lineTo(-7,1);ctx.lineTo(-19,-1);ctx.fill();ctx.beginPath();ctx.moveTo(20,-12);ctx.lineTo(4,-6);ctx.lineTo(7,1);ctx.lineTo(19,-1);ctx.fill();ctx.shadowColor='#ed737a';ctx.shadowBlur=close?13:6;ctx.globalAlpha=glow+.3;roundRect(-16,-6,8,3,1,'#e89996');roundRect(8,-6,8,3,1,'#e89996');ctx.globalAlpha=1;ctx.shadowBlur=0;ctx.strokeStyle='#baa4a4';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(-8,7);ctx.lineTo(8,7);ctx.stroke();
}else{
// A vintage spray-bottle pendulum with an ominous eye-shaped label.
const glass=ctx.createLinearGradient(-21,0,21,0);glass.addColorStop(0,'#356567');glass.addColorStop(.3,'#83a8a2');glass.addColorStop(.6,'#557e7d');glass.addColorStop(1,'#243d49');ctx.fillStyle=glass;ctx.beginPath();ctx.moveTo(-9,-25);ctx.lineTo(9,-25);ctx.lineTo(11,-15);ctx.quadraticCurveTo(22,-10,23,8);ctx.lineTo(22,27);ctx.quadraticCurveTo(0,33,-22,27);ctx.lineTo(-23,8);ctx.quadraticCurveTo(-23,-9,-11,-15);ctx.closePath();ctx.fill();roundRect(-12,-33,27,9,3,'#b1a17f');roundRect(8,-34,18,6,2,'#cab997');ctx.strokeStyle='#cab997';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(7,-25);ctx.lineTo(17,-14);ctx.stroke();roundRect(-13,-1,26,22,3,'#263d45');ctx.save();ctx.shadowColor='#b681b1';ctx.shadowBlur=9;ctx.fillStyle='#c09bb7';ctx.beginPath();ctx.moveTo(-9,10);ctx.quadraticCurveTo(0,-1,9,10);ctx.quadraticCurveTo(0,19,-9,10);ctx.fill();ctx.fillStyle='#283544';ctx.fillRect(-1,4,2,12);ctx.restore();ctx.strokeStyle='#cde1d47a';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-16,-5);ctx.quadraticCurveTo(-19,7,-17,18);ctx.stroke();
if(close){for(let k=0;k<6;k++){const phase=(t*.65+k/6)%1;ctx.globalAlpha=(1-phase)*.24;ctx.fillStyle='#ccc3e0';ctx.beginPath();ctx.ellipse(26+phase*52,-31+Math.sin(k*4)*phase*24,3+phase*11,2+phase*6,0,0,7);ctx.fill();}ctx.globalAlpha=1;}}
ctx.restore();}
function bloom(x,y,r,angle=0,open=true){ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.fillStyle=open?'#c9accf':'#777d9d';ctx.strokeStyle='#efdfb7';ctx.lineWidth=1;for(let i=0;i<6;i++){ctx.rotate(Math.PI/3);ctx.beginPath();ctx.ellipse(0,-r*.47,open?r*.3:r*.18,r*.55,0,0,Math.PI*2);ctx.fill();ctx.stroke();}ctx.fillStyle='#f6dc9c';ctx.beginPath();ctx.arc(0,0,r*.18,0,7);ctx.fill();ctx.restore();}
function drawGardenBackground(){const sky=ctx.createLinearGradient(0,0,0,H);sky.addColorStop(0,['#171d36','#30213a','#183437'][floor]);sky.addColorStop(.65,'#45415c');sky.addColorStop(1,'#1a2533');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);const mx=W*.72-camera*.06;const halo=ctx.createRadialGradient(mx,100,20,mx,100,165);halo.addColorStop(0,'#ece5d232');halo.addColorStop(1,'#ece5d200');ctx.fillStyle=halo;ctx.fillRect(mx-165,0,330,265);ctx.fillStyle='#eee4cf';ctx.beginPath();ctx.arc(mx,103,45,0,7);ctx.fill();ctx.fillStyle='#29283f';ctx.beginPath();ctx.arc(mx+20,87,43,0,7);ctx.fill();
for(let i=0;i<55;i++){ctx.globalAlpha=.2+(Math.sin(t*.7+i)+1)*.2;ctx.fillStyle='#eaddeb';ctx.beginPath();ctx.arc((i*137.7-camera*.08+W*4)%W,35+(i*47)%260,i%4===0?1.6:.7,0,7);ctx.fill();}ctx.globalAlpha=1;
for(let i=0;i<9;i++){const x=i*290-camera*.28-60;ctx.strokeStyle='#9892a529';ctx.lineWidth=16;ctx.beginPath();ctx.moveTo(x,groundY);ctx.lineTo(x,259);ctx.bezierCurveTo(x,150,x+144,150,x+144,259);ctx.lineTo(x+144,groundY);ctx.stroke();ctx.lineWidth=2;ctx.strokeStyle='#d7c8c738';ctx.stroke();ctx.strokeStyle='#536b6866';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x-8,groundY);for(let j=0;j<14;j++){ctx.lineTo(x+Math.sin(j*1.7)*14,groundY-j*20);}ctx.stroke();for(let j=0;j<10;j++){ctx.fillStyle='#72917b55';ctx.beginPath();ctx.ellipse(x+Math.sin(j*1.7)*14,groundY-j*25,14,4,j*.8,0,7);ctx.fill();}}
for(let layer=0;layer<3;layer++){ctx.fillStyle=['#3e4c5a','#344d51','#263e43'][layer];ctx.beginPath();ctx.moveTo(0,H);for(let x=0;x<=W+30;x+=30)ctx.lineTo(x,420+layer*23+Math.sin((x+camera*(.12+layer*.08))/90+layer)*19);ctx.lineTo(W,H);ctx.fill();}
for(let i=0;i<22;i++){const x=((i*97+t*12-camera*.18)%(W+100)+W+100)%(W+100)-50,y=80+(i*57+t*7)%390;ctx.save();ctx.translate(x,y);ctx.rotate(Math.sin(t*.5+i));ctx.fillStyle=i%2?'#e1bdd071':'#c7d5b678';ctx.beginPath();ctx.ellipse(0,0,4,1.8,0,0,7);ctx.fill();ctx.restore();}}
function drawGardenPlants(a,b){ctx.strokeStyle='#678672';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(a,groundY+3);ctx.lineTo(b,groundY+3);ctx.stroke();for(let x=a+16;x<b-8;x+=39){const y=groundY-2,h=10+(x%23);ctx.strokeStyle='#75917c';ctx.lineWidth=1.2;ctx.beginPath();ctx.moveTo(x,y);ctx.quadraticCurveTo(x-5,y-h*.5,x+2,y-h);ctx.stroke();ctx.fillStyle='#789984';ctx.beginPath();ctx.ellipse(x-4,y-h*.4,7,2.6,.4,0,7);ctx.fill();if(x%3===1)bloom(x+2,y-h,5+x%3,Math.sin(t+x)*.1);}}
const gardenHints=['荊棘發光後會升起，等它收攏再通過','月蛾低飛時先停步，趁牠飛高或轉身時穿越','花心亮起是噴霧預告，等花粉散去再前進'];
function gardenHazard(i,clock=gardenTime,area=floor){const base=860+i*640;
if(area===1)return{kind:'moth',x:base+Math.sin(clock*1.15+i*2)*100,y:405+Math.sin(clock*.85+i*1.7)*43,w:58,h:40,active:true,warning:false,phase:clock};
const cycle=area===0?5.8:6.2,p=(clock+i*2.1)%cycle,safe=area===0?2.6:2.9,warn=.9,active=p>=safe+warn;
return{kind:area===0?'thorn':'pollen',x:base,y:groundY,w:area===0?70:64,h:area===0?108:185,active,warning:p>=safe&&!active,phase:p,cycle,safe,remaining:p<safe?safe-p:cycle-p};}
function gardenHit(h){if(!h.active)return false;const left=cat.x-16,right=cat.x+16,top=cat.y-27,bottom=cat.y+36;return h.kind==='moth'?left<h.x+h.w/2&&right>h.x-h.w/2&&top<h.y+h.h/2&&bottom>h.y-h.h/2:left<h.x+h.w/2&&right>h.x-h.w/2&&bottom>h.y-h.h&&top<h.y;}
function drawGardenChallenge(h){ctx.save();ctx.translate(h.x,h.y);if(h.kind==='moth'){
// A patrol route and drifting moon moth; no hanging rod or pivot.
ctx.strokeStyle='#d8cee72b';ctx.lineWidth=1;ctx.setLineDash([3,7]);ctx.beginPath();ctx.moveTo(-120,-8);ctx.quadraticCurveTo(0,-28,120,-8);ctx.stroke();ctx.setLineDash([]);const flap=.62+Math.sin(gardenTime*11)*.25;ctx.shadowColor='#cbbce3';ctx.shadowBlur=18;for(const side of [-1,1]){ctx.save();ctx.scale(side,1);ctx.fillStyle='#c8b5da';ctx.beginPath();ctx.ellipse(17,-9,23*flap,17,-.55,0,7);ctx.fill();ctx.fillStyle='#8d8cad';ctx.beginPath();ctx.ellipse(14,10,17*flap,12,.4,0,7);ctx.fill();ctx.fillStyle='#f0ddaa';ctx.beginPath();ctx.arc(19,-7,4,0,7);ctx.fill();ctx.restore();}ctx.shadowBlur=0;ctx.strokeStyle='#f1e2c4';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(0,-16);ctx.lineTo(0,17);ctx.stroke();ctx.lineWidth=1;for(const side of [-1,1]){ctx.beginPath();ctx.moveTo(0,-15);ctx.quadraticCurveTo(side*5,-26,side*11,-25);ctx.stroke();}ctx.fillStyle='#d9cbe8';ctx.font='11px sans-serif';ctx.textAlign='center';ctx.fillText('月蛾巡遊',0,-42);
}else{const color=h.active?'#e4a8c7':h.warning?'#e9c990':'#a8cbb3';ctx.fillStyle='#182a32';ctx.beginPath();ctx.ellipse(0,1,44,9,0,0,7);ctx.fill();
if(h.kind==='thorn'){const growth=h.active?Math.min(1,(h.phase-h.safe-.9)/.20):0;for(let j=-2;j<=2;j++){const x=j*14,height=10+(h.h-10-Math.abs(j)*8)*growth;ctx.strokeStyle=h.active?'#ad91b0':'#718e7c';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(x,0);ctx.bezierCurveTo(x-13,-height*.4,x+12,-height*.7,x,-height);ctx.stroke();if(growth>.1){ctx.fillStyle='#d6a8c5';for(let k=1;k<4;k++){const yy=-height*k/4;ctx.beginPath();ctx.moveTo(x,yy+5);ctx.lineTo(x+(k%2?-11:11),yy-7);ctx.lineTo(x,yy-2);ctx.fill();}}}if(h.warning){ctx.shadowColor='#e5ba85';ctx.shadowBlur=12;for(let j=-2;j<=2;j++)bloom(j*14,-12,5,0,false);ctx.shadowBlur=0;}
}else{bloom(0,-12,22,gardenTime*.06,h.active||h.warning);if(h.active){const fog=ctx.createLinearGradient(0,-h.h,0,0);fog.addColorStop(0,'#d5acc700');fog.addColorStop(.35,'#d5acc74a');fog.addColorStop(1,'#d9c3dc88');ctx.fillStyle=fog;ctx.fillRect(-h.w/2,-h.h,h.w,h.h-10);for(let k=0;k<24;k++){const phase=(gardenTime*1.15+k/24)%1;ctx.globalAlpha=(1-phase)*.8;ctx.fillStyle=k%2?'#edd4a1':'#dac1e7';ctx.beginPath();ctx.arc(Math.sin(k*6+gardenTime)*h.w*.43,-15-phase*(h.h-15),1.5+k%3,0,7);ctx.fill();}ctx.globalAlpha=1;}if(h.warning){ctx.shadowColor='#efd08f';ctx.shadowBlur=20;ctx.fillStyle='#f7daa2';ctx.beginPath();ctx.arc(0,-12,7+Math.sin(gardenTime*12)*2,0,7);ctx.fill();ctx.shadowBlur=0;}}
ctx.fillStyle=color;ctx.font='11px sans-serif';ctx.textAlign='center';ctx.fillText(h.active?(h.kind==='thorn'?'荊棘升起':'花粉噴發'):h.warning?(h.kind==='thorn'?'荊棘蓄勢 · 等一下':'花心發光 · 等一下'):'空檔 · 可以通過',0,-h.h-24);ctx.fillStyle='#121e3088';ctx.fillRect(-28,-h.h-15,56,3);ctx.fillStyle=color;ctx.fillRect(-28,-h.h-15,56*(h.remaining/(h.active||h.warning?h.cycle-h.safe:h.safe)),3);
}ctx.restore();}
function draw(){ctx.clearRect(0,0,W,H);if(chapter===1){drawGardenBackground();}else{const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,['#242b3d','#302739','#3b2c2c','#293039'][floor]);g.addColorStop(1,'#151b28');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);
if(img.complete&&img.naturalWidth){ctx.globalAlpha=.13;ctx.drawImage(img,0,0,img.width,img.height*.85,0,0,W,H);ctx.globalAlpha=1;}
const par=camera*.25;ctx.strokeStyle='#c6c4b00a';ctx.lineWidth=2;for(let y=0;y<groundY;y+=65){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke();for(let x=-par%155+(y%130?70:0);x<W;x+=155){ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x,y+65);ctx.stroke();}}
for(let i=0;i<8;i++){const x=180+i*340-camera*.4;if(x<-180||x>W+180)continue;ctx.save();ctx.fillStyle='#111823';ctx.beginPath();ctx.roundRect(x-44,100,88,215,[44,44,0,0]);ctx.fill();const lg=ctx.createLinearGradient(0,100,0,315);lg.addColorStop(0,currentFloors()[floor].color+'75');lg.addColorStop(1,currentFloors()[floor].color+'05');ctx.fillStyle=lg;ctx.beginPath();ctx.roundRect(x-37,108,74,200,[37,37,0,0]);ctx.fill();ctx.fillStyle='#33343c';ctx.fillRect(x-3,110,6,198);ctx.fillRect(x-37,193,74,6);ctx.restore();}
for(let i=0;i<7;i++){gear(100+i*310-camera*.58,80+(i%2)*155,55+(i%3)*15,t*(i%2?.16:-.13),.36);}
for(let i=0;i<35;i++){const px=((i*97+t*(8+i%5))-camera*.2)%(W+70),py=(i*59+Math.sin(t*.5+i)*12)%480;ctx.fillStyle='#ead29b';ctx.globalAlpha=.15+(Math.sin(t+i)+1)*.13;ctx.beginPath();ctx.arc(px,py,1+i%2,0,7);ctx.fill();}ctx.globalAlpha=1;}
ctx.save();ctx.translate(-camera,0);const segments=[[0,425],[515,1065],[1155,1705],[1795,worldWidth]];
for(const [a,b]of segments){const gg=ctx.createLinearGradient(0,groundY,0,H);gg.addColorStop(0,'#626474');gg.addColorStop(.14,'#363b4b');gg.addColorStop(1,'#171b29');ctx.fillStyle=gg;ctx.fillRect(a,groundY,b-a,H-groundY);ctx.fillStyle='#b6b0a5';ctx.fillRect(a,groundY,b-a,5);ctx.fillStyle='#cdb99155';ctx.fillRect(a,groundY+7,b-a,2);ctx.strokeStyle='#141c2860';ctx.lineWidth=2;for(let x=a;x<b;x+=78){ctx.strokeRect(x,groundY+15,78,42);ctx.strokeRect(x-35,groundY+58,78,44);}}
if(chapter===1)for(const [a,b]of segments)drawGardenPlants(a,b);
for(let i=0;i<3;i++){const gx=gates[i],done=solved.has(floor*3+i);ctx.strokeStyle=done?'#96cfa340':'#d9b977';ctx.lineWidth=5;ctx.beginPath();ctx.roundRect(gx-15,groundY-225,64,225,[30,30,0,0]);ctx.stroke();if(!done){const beam=ctx.createLinearGradient(gx,0,gx+35,0);beam.addColorStop(0,'#e5c17608');beam.addColorStop(.5,'#f2d19499');beam.addColorStop(1,'#e5c17608');ctx.fillStyle=beam;ctx.fillRect(gx-10,groundY-210,55,210);}roundRect(gx-85,groundY-56,27,56,3,'#5a4e41');ctx.save();ctx.shadowColor=done?'#98e5bc':'#e6bb66';ctx.shadowBlur=24;if(chapter===1)bloom(gx-72,groundY-77,32,done?t*.1:0,done);else gear(gx-72,groundY-77,32,done?t*.5:0);ctx.restore();ctx.fillStyle=done?'#b3e1be':'#f5dc9e';ctx.font='bold 17px Georgia';ctx.textAlign='center';ctx.fillText(done?'✓':String(floor*3+i+1).padStart(2,'0'),gx-72,groundY-118);if(done){ctx.fillStyle='#dfc78c';ctx.beginPath();ctx.moveTo(gx-72,groundY-156);ctx.lineTo(gx-65,groundY-146);ctx.lineTo(gx-72,groundY-136);ctx.lineTo(gx-79,groundY-146);ctx.fill();}}
for(let i=0;i<2;i++){if(chapter===1){drawGardenChallenge(gardenHazard(i));continue;}const h=hazard(i);ctx.strokeStyle='#a89062';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(h.ax,200);ctx.lineTo(h.x,h.y);ctx.stroke();const rg=ctx.createRadialGradient(h.x-10,h.y-10,1,h.x,h.y,26);rg.addColorStop(0,'#e6c886');rg.addColorStop(1,'#856237');ctx.fillStyle=rg;ctx.beginPath();ctx.arc(h.x,h.y,26,0,7);ctx.fill();ctx.strokeStyle='#dec18a';ctx.lineWidth=2;ctx.beginPath();ctx.arc(h.x,h.y,20,0,7);ctx.stroke();if(floor===1||floor===2)drawHauntedWeight(h,i);gear(h.ax,200,25,t*.2);}
const endX=worldWidth-85;ctx.fillStyle='#d5c69225';ctx.beginPath();ctx.roundRect(endX-15,groundY-150,80,150,[40,40,0,0]);ctx.fill();ctx.strokeStyle='#d7b775';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle='#dfc995';ctx.font='12px sans-serif';ctx.textAlign='center';ctx.fillText(floor===currentFloors().length-1?(chapter===1?'花園之門':'第二道輪盤'):(chapter===1?'下一座庭院':'前往上一層'),endX+25,groundY-172);for(let i=0;i<5;i++)roundRect(endX-20+i*12,groundY-5-i*11,60-i*8,6,1,'#9c907b');
ctx.fillStyle='#0005';ctx.beginPath();ctx.ellipse(cat.x,groundY+1,24,5,0,0,7);ctx.fill();drawCat(cat.x,cat.y);ctx.restore();
const vignette=ctx.createLinearGradient(0,H-70,0,H);vignette.addColorStop(0,'#11172300');vignette.addColorStop(1,'#111723aa');ctx.fillStyle=vignette;ctx.fillRect(0,H-70,W,70);}
function finish(){transition=false;screen('ending');$('end-eyebrow').textContent='CERTIFICATE OF COMPLETION';$('end-title').textContent=chapter===1?'The Garden of What If':'The Tower of Time';$('end-description').textContent=chapter===1?'You have explored possibility, discovered hope, and helped every wish bloom.':'With courage and curiosity, you have unlocked every gate.';$('final-shards').textContent=gateCount;$('final-shard-label').textContent=chapter===1?'Seeds of possibility collected':'Time shards collected';$('next-chapter').classList.toggle('hidden',chapter!==0);$('replay-interlude').classList.toggle('hidden',chapter!==0);$('again').textContent=chapter===1?'再探一次未然之庭 ↗':'重玩時間之塔';$('final-score').textContent=firstCorrect;$('final-total').textContent=totalQuestions;$('end-message').textContent=firstCorrect===totalQuestions?'Every challenge solved on your first try. Remarkable work!':'Every challenge completed. Every discovery is a step forward.';try{const accuracy=Math.round(firstCorrect/totalQuestions*100),best=Math.max(accuracy,Number(localStorage.getItem((chapter===1?'cat-garden-best-rate':'cat-time-best-rate'))||0));localStorage.setItem((chapter===1?'cat-garden-best-rate':'cat-time-best-rate'),best);localStorage.setItem('cat-time-played-v2','1');}catch{}$('review-list').replaceChildren();if(!mistakes.size){const el=document.createElement('div');el.className='review-good';el.textContent=chapter===1?'這次沒有錯題！記住：假設現在不同，常用過去式；假設過去不同，用 had＋過去分詞。wish 也要先分清現在的願望與過去的遺憾。':'這次沒有錯題！記住：先看事件發生的時間，再判斷它是習慣、進行中的動作，還是與另一個時間點有連結。';$('review-list').appendChild(el);}else for(const i of mistakes){const q=QUESTIONS[i],el=document.createElement('article');el.className='review-item';const small=document.createElement('small');const gate=rounds.findIndex(r=>r.includes(i));small.textContent='機關 '+String(gate+1).padStart(2,'0')+' · '+q.clue;const title=document.createElement('b');title.style.display='block';let text=q.text;if(q.options[q.answer].includes(' / ')){for(const part of q.options[q.answer].split(' / '))text=text.replace('___',part);}else text=text.replace('___',q.options[q.answer]);title.textContent=text;const p=document.createElement('p');p.textContent=q.why;el.append(small,title,p);$('review-list').appendChild(el);}chime();if(chapter===0)playInterlude();}
try{if(localStorage.getItem('cat-time-played-v2'))$('best').textContent='最佳首次答對率：'+(localStorage.getItem((chapter===1?'cat-garden-best-rate':'cat-time-best-rate'))||0)+'%';}catch{}
function frame(now){const dt=Math.min((now-lastTime)/1000||0,.025);lastTime=now;if(mode==='game'){update(dt);draw();}requestAnimationFrame(frame);}requestAnimationFrame(frame);

// Begin at the game title; one paw tap starts the original prologue with sound.
screen('home');

// A self-contained keepsake with the chapter and actual result from this run.
$('save-certificate').onclick=()=>{const c=document.createElement('canvas');c.width=1800;c.height=1200;const x=c.getContext('2d');x.fillStyle='#f6efdf';x.fillRect(0,0,1800,1200);x.strokeStyle='#b89452';x.lineWidth=3;x.strokeRect(42,42,1716,1116);x.lineWidth=1;x.strokeRect(57,57,1686,1086);for(const [px,py]of [[85,85],[1715,85],[85,1115],[1715,1115]]){x.save();x.translate(px,py);x.rotate(Math.PI/4);x.fillStyle='#b89452';x.fillRect(-7,-7,14,14);x.restore();}x.textAlign='center';function line(text,y,size,color='#433a35',font='Georgia'){x.fillStyle=color;x.font=size+'px '+font;x.fillText(text,900,y,1580);}line('THE CAT CHRONICLES',140,23,'#91733e');line('CERTIFICATE OF COMPLETION',220,35,'#91733e');x.strokeStyle='#b89452';x.beginPath();x.arc(900,316,52,0,Math.PI*2);x.stroke();x.fillStyle='#b89452';for(const [px,py,rx,ry]of [[873,301,9,12],[891,287,9,12],[911,287,9,12],[929,301,9,12],[900,327,24,19]]){x.beginPath();x.ellipse(px,py,rx,ry,0,0,Math.PI*2);x.fill();}line('Congratulations, brave adventurer!',423,39);line('You have completed the trials of',482,25);line(chapter===1?'The Garden of What If':'The Tower of Time',575,76,'#715631');line('With courage and curiosity, you have completed every challenge.',646,25);line(firstCorrect+' / '+totalQuestions+' first-try answers     ·     '+gateCount+' / '+gateCount+' gates unlocked',731,28);line('Let us journey onward,',839,35);line('into adventures yet unknown.',888,35);line('Sharon Grammar Lab',1000,37,'#715631');line('AWARDED FOR COMPLETING THIS CHAPTER',1050,17,'#91733e');c.toBlob(blob=>{if(!blob){toast('證書暫時無法儲存，請再試一次。');return;}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=chapter===1?'The-Garden-of-What-If-Certificate.png':'The-Tower-of-Time-Certificate.png';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);},'image/png');};
